In [11]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


🌟 Exercise 1 : Array Creation and Manipulation

In [12]:
import numpy as np

In [13]:
array_1D = np.arange(10)
array_1D

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

🌟 Exercise 2 : Type Conversion and Array Operations

In [14]:
liste = [3.14, 2.17, 0, 1, 2]
array = np.array(liste)
array

array([3.14, 2.17, 0.  , 1.  , 2.  ])

🌟 Exercise 3 : Working with Multi-Dimensional Arrays

In [15]:
array_2D = np.array([range(1,4), range(4,7), range(7, 10)])
array_2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

🌟 Exercise 4 : Creating Multi-Dimensional Array with Random Numbers

In [16]:
random_array = np.random.rand(4, 5)
random_array

array([[0.93560099, 0.84353632, 0.96029729, 0.49674404, 0.85550439],
       [0.35866189, 0.20622805, 0.11500672, 0.8043844 , 0.56570291],
       [0.45107222, 0.07795584, 0.01542397, 0.31440486, 0.98863347],
       [0.78084323, 0.62221312, 0.52281333, 0.79110227, 0.027832  ]])

🌟 Exercise 5 : Indexing Arrays

In [17]:
array_2D[1]

array([4, 5, 6])

🌟 Exercise 6 : Reversing elements

In [25]:
reversed_array = array_1D[::-1]
reversed_array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

🌟 Exercise 7 : Identity Matrix

In [19]:
identity_matrix = np.eye(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

🌟 Exercise 8 : Simple Aggregate Funcs

In [20]:
array_1D_sum = array_1D.sum()
array_1D_mean = array_1D.mean()
print(f"Sum: {array_1D_sum}, Average: {array_1D_mean}")

Sum: 45, Average: 4.5


🌟 Exercise 9 : Create Array and Change its Structure

In [21]:
reshaped_array = np.arange(1,21).reshape(4,5)
reshaped_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

🌟 Exercise 10 : Conditional Selection of Values

In [26]:
odd_number = array_1D[1::2]
odd_number

array([1, 3, 5, 7, 9])