In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


🌟 Exercise 1 : Array Creation and Manipulation

In [2]:
import numpy as np

In [3]:
array_1D = np.array(range(10))
array_1D

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

🌟 Exercise 2 : Type Conversion and Array Operations

In [4]:
liste = [3.14, 2.17, 0, 1, 2]
array = np.array(liste)
array

array([3.14, 2.17, 0.  , 1.  , 2.  ])

🌟 Exercise 3 : Working with Multi-Dimensional Arrays

In [5]:
array_2D = np.array([range(1,4), range(4,7), range(7, 10)])
array_2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

🌟 Exercise 4 : Creating Multi-Dimensional Array with Random Numbers

In [6]:
random_array = np.random.rand(4, 5)
random_array

array([[0.94747283, 0.63768853, 0.54852132, 0.91544908, 0.61947696],
       [0.37866857, 0.11272076, 0.70187741, 0.87384491, 0.33052865],
       [0.36513232, 0.50638035, 0.39805128, 0.80233256, 0.52311215],
       [0.87306676, 0.44747518, 0.06622939, 0.89228048, 0.17022073]])

🌟 Exercise 5 : Indexing Arrays

In [7]:
array_2D[1]

array([4, 5, 6])

🌟 Exercise 6 : Reversing elements

In [8]:
reversed_array = array_1D[::-1]
reversed_array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

🌟 Exercise 7 : Identity Matrix

In [9]:
identity_matrix = np.eye(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

🌟 Exercise 8 : Simple Aggregate Funcs

In [10]:
array_1D_sum = array_1D.sum()
array_1D_mean = array_1D.mean()
print(f"Sum: {array_1D_sum}, Average: {array_1D_mean}")

Sum: 45, Average: 4.5


🌟 Exercise 9 : Create Array and Change its Structure

In [11]:
reshaped_array = np.array(range(1,21)).reshape(4,5)
reshaped_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

🌟 Exercise 10 : Conditional Selection of Values

In [16]:
odd_number = array_1D[1::2]
odd_number

array([1, 3, 5, 7, 9])